// import './globals.css'
import "./globals-tw.css";

export const metadata = {
  title: "QRCode Generator API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
